root: true
env:
  node: true
  browser: true
parserOptions:
  ecmaVersion: 5
  sourceType: script
extends: semistandard
rules:
  strict:
    - error
    - safe
  linebreak-style:
    - error
    - unix
