root: true
extends:
  - semistandard
  - plugin:prettier/recommended
env:
  node: yes
  browser: yes
parserOptions:
  ecmaVersion: 5
  ecmaFeatures:
    globalReturn: no
    experimentalObjectRestSpread: no
    jsx: no
  sourceType: script
rules:
  strict:
    - error
    - safe
overrides:
  - files:
    - scripts/**/*.js
    - package-scripts.js
    - karma.conf.js
    - .wallaby.js
    - bin/*
    - lib/cli/**/*.js
    - test/node-unit/**/*.js
    parserOptions:
      ecmaVersion: 6
    env:
      browser: no
  - files:
    - test/**/*.{js,mjs}
    env:
      mocha: yes
    globals:
      expect: no
  - files:
    - doc/**/*.js
    env:
      node: no
  - files:
    - test/**/*.mjs
    parserOptions:
      ecmaVersion: 6
      sourceType: module

