name: Auto-add item to Mocha project

# Automatically adds issues to our GitHub project
# We silence all failures to reduce noise
# https://markwiemer.com/software/github/apps#auto-add

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      # https://github.com/actions/create-github-app-token
      # https://github.com/mochajs/mocha/settings/secrets/actions
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: mark-wiemer-org
      # https://github.com/actions/add-to-project
      - uses: actions/add-to-project@v2
        with:
          project-url: https://github.com/orgs/mochajs/projects/6
          github-token: ${{ steps.app-token.outputs.token }}