name: Blocked PR Check

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: read

jobs:
  not-blocked:
    name: not-blocked
    runs-on: ubuntu-latest
    steps:
      - name: 'Verify "status: blocked" label is not applied'
        if: contains(github.event.pull_request.labels.*.name, 'status: blocked')
        run: |
          echo "::error::This PR has the 'status: blocked' label and cannot be merged until that label is removed."
          exit 1
