name: Blocked PR Check

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: read

jobs:
  not-blocked:
    name: not-blocked
    runs-on: ubuntu-latest
    steps:
      - name: 'Verify "status: blocked" label is not applied'
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 0
          labels: "status: blocked"
          message: "This PR has the 'status: blocked' label and cannot be merged until that label is removed."
