name: Browser Tests for forked PRs

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: read
  pull-requests: write

jobs:
  test-browser:
    # TODO: configure to retain build artifacts in `.karma/` dir
    name: 'Browser Tests'
    timeout-minutes: 20
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-browser-test')
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Browser Tests
        run: npm start test.browser
        env:
          SAUCE_USERNAME: '${{secrets.SAUCE_USERNAME}}'
          SAUCE_ACCESS_KEY: '${{secrets.SAUCE_ACCESS_KEY}}'
      - name: remove 'run-browser-test' label
        uses: buildsville/add-remove-label@v2.0.1
        if: ${{ always() }}
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: run-browser-test
          type: remove
