name: Browser Tests for forked PRs

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: read
  pull-requests: write

jobs:
  test-browser:
    name: 'Browser Tests'
    if: contains(github.event.pull_request.labels.*.name, 'run-browser-test')
    uses: ./.github/workflows/npm-script.yml
    secrets: inherit
    with:
      npm-script: test.browser

  remove-label:
    needs: test-browser
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: remove 'run-browser-test' label
        uses: buildsville/add-remove-label@ac59c9f0aeb66eb12d6366eb1d69ec1906e9ef9a
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: run-browser-test
          type: remove
