jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install --ignore-scripts
      - run: npm run lint

name: CI

on:
  pull_request: ~
  push:
    branches:
      - main
