name: Tests

on:
  push:
    branches:
      - main
    paths-ignore: ['*.md', 'docs/**']
  pull_request:
    branches:
      - main
    paths-ignore: ['*.md', 'docs/**']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-node-all:
    name: Test ${{ matrix.test-part }} in all environments
    # TODO: Restore "mocha-github-actions-reporter" style reporting without relying on third party module
    uses: ./.github/workflows/npm-script.yml
    needs: test-node-lts
    strategy:
      fail-fast: false
      matrix:
        coverage: [true]
        test-part:
          - integration
        include:
          - test-part: jsapi
            coverage: false
    with:
      os: 'ubuntu-latest,windows-latest'
      # The 20.18.3 is instead of 20 per https://github.com/mochajs/mocha/issues/5052
      # The 22.11.0 is instead of 22 per https://github.com/mochajs/mocha/issues/5278
      node-versions: '18,20.18.3,22.11.0,24'
      npm-script: test-node:${{ matrix.test-part }}
      coverage: ${{ matrix.coverage }}

  # test-browser-saucelabs:
  #   # Don't run forked 'pull_request' without saucelabs token
  #   if: github.event_name == 'push' || !github.event.pull_request.head.repo.fork
  #   needs:
  #     - lint
  #     - smoke
  #     - test-browser-local
  #   uses: ./.github/workflows/npm-script.yml
  #   secrets: inherit
  #   with:
  #     browsers: 'firefox@latest,chrome@latest,MicrosoftEdge@latest,safari@latest'
  #     npm-script: test-browser
