# Deletes expired artifacts, which are not removed automatically by github.

name: 'Purge expired artifacts'

on:
  schedule:
    - cron: '0 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  purge-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: LKP-RnD/purge-expired-artifacts-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo_to_purge: "mochajs/mocha"
          dry_run: "false"
